### ISSUE TITLE
distorted STL. Adjusting STL wrong?

### ISSUE THREAD

**Issue by kwetter** [wredenberg/FAME#1]
I know its an old project that might not be developed anymore. I still wnat to try my luck.

I get the script working with all the dependencies on Ubuntu 18. Calculix does its solving but the adjusted STL is very distorted. Even with the testartifact.stl.

any suggestions?

**Comment by wredenberg** [comment]
Hi

Are you possibly using a Calculix version < 2.14?

**Comment by kwetter** [comment]
Hey there

that was it! I installed calculix through apt-get repositories which dont include the latest version of Calculix. A manual installation of calculix 2.15 solved the problem. Thanks for the input!
