### ISSUE TITLE
Error reading *NODE, Card Image:..

### ISSUE THREAD

**Issue by kwetter** [wredenberg/FAME#2]
Sorry to bother again.
I got the script working with the testArtifact.stl. 
Trials with other STL files always result in a Calculix "Error reading *Node, Card Image"

What am I missing?

In- and Output files:
[ccx_output.txt](https://github.com/Swerim/FAME/files/3524677/ccx_output.txt)
[am.inp.txt](https://github.com/Swerim/FAME/files/3524681/am.inp.txt)
[geom.inp.txt](https://github.com/Swerim/FAME/files/3524682/geom.inp.txt)

Dependecies installed as required (except: I am using latest Calculix 2.15 instead of 2.13.1)

**Comment by wredenberg** [comment]
Could you share a STL that gives you this problem?

**Comment by kwetter** [comment]
I used a few generic STLs I quickly modelled, same result. There might be something wrong with my workflow, but i couldn't guess what. Attached the file that results in the mentioned output. (remove the .txt ending).

Edit: I just ran one simulation with a slightly editet testArtifact.stl (same workflow). Seems to run properly. But i still cant tell what im doing wrong with the other stls.

[test3.stl.txt](https://github.com/Swerim/FAME/files/3525702/test3.stl.txt)

**Comment by wredenberg** [comment]
I think it's having trouble with the cylindrical build plate. Try a rectangular hexahedron instead. 

I never thought anyone would use a cylindrical one. Do you have this type of machine?

**Comment by kwetter** [comment]
I adjusted my build plate to a hexahedron and started a simulation. No error messages so far, so it seems to work, meaning you were right: The script does not accept cylindrical build plates. 

I do have a machine with cylindrical build plate (The company TRUMPF is a few of the manufacturers that make such powder bde machines). The approximation with a rectangular build plate should suffice though, at least for now.

Thanks for the help!
